name: Semantic Versioning

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0

      - name: Output calculated version
        run: |
          echo "Calculated version: ${{ steps.gitversion.outputs.semVer }}"
          echo "Major version: ${{ steps.gitversion.outputs.major }}"
          echo "Minor version: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch version: ${{ steps.gitversion.outputs.patch }}"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -a "v${{ steps.gitversion.outputs.semVer }}" -m "Release version ${{ steps.gitversion.outputs.semVer }}"
          git push origin "v${{ steps.gitversion.outputs.semVer }}"